[project]
ref = "wvrhxxtvefeyynglfibq"
name = "oki-app"

[api]
port = 54321
schemas = ["public", "storage"]

[db.migrations]
directory = "./migrations"

[analytics]
enabled = false

[functions]
enabled = true

[functions.kyc-upload]
verify_jwt = false
import_map = "./import_map.json"

[functions.submit-onboarding]
verify_jwt = false
import_map = "./import_map.json"

[functions.kyc-admin-list]
verify_jwt = true
import_map = "./import_map.json"

[functions.kyc-admin-review]
verify_jwt = true
import_map = "./import_map.json"

[functions.accept-booking]
verify_jwt = true
import_map = "./import_map.json"

[functions.complete-booking]
verify_jwt = true
import_map = "./import_map.json"

[functions.payment-webhook]
verify_jwt = false
import_map = "./import_map.json"

[functions.seed]
verify_jwt = false
import_map = "./import_map.json"

[auth]
enabled = true

[storage]
enabled = true
